#!/bin/bash
echo "coba jadi manusia yang berguna bagi orang tua"
Traveloka
arn : bahtiar.widayanto@traveloka.com status:probation --> status:karyawan tetap
arn : ningrum@traveloka.com
arn : balya@traveloka.com
arn : serumah@traveloka.com
arn : kajen@traveloka.com
