#!/bin/bash
echo "coba jadi manusia yang berguna bagi orang tua"
Traveloka
arn : bahtiar.widayanto@traveloka.com status:probation
arn : ningrum@traveloka.com
arn : balya@traveloka.com
arn : serumah@traveloka.com
